services:
  web:
    build: . # . means the file is in the current directory
    ports:
      - "5000:80" # like the one on the dockerfile
    volumes:
      - .:/app # copy and keep in sync the docker folder set in the dockerfile and local folder
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U postgres
      interval: 2s
      retries: 10
volumes:
  postgres_data: